name: MacOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install ninja
          git clone https://github.com/microsoft/vcpkg.git ${{github.workspace}}/vcpkg
          ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=${{github.workspace}}/vcpkg" >> $GITHUB_ENV
      - name: Build
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build --preset="debug" -G "Ninja"
          cmake --build ${{github.workspace}}/build
      - name: Test
        shell: bash
        run: |
          cd ${{github.workspace}}/build
          ctest -V
      - name: Install
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/release --preset="release" -G "Ninja"
          cmake --build ${{github.workspace}}/release
          sudo cmake --install ${{github.workspace}}/release
      - name: Build Example
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/example/build -S ${{github.workspace}}/example
          cmake --build ${{github.workspace}}/example/build