name: Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          choco install cmake
          git clone https://github.com/microsoft/vcpkg.git ${{github.workspace}}/vcpkg
          ${{github.workspace}}\vcpkg\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=${{github.workspace}}\\vcpkg" >> $env:GITHUB_ENV
      - name: Build (debug)
        shell: bash
        run: |
          mkdir build
          cmake -B build --preset="debug"
          cmake --build build --config Debug
      - name: Test
        shell: bash
        run: |
          cd build
          ctest -V
      - name: Build (release)
        shell: bash
        run: |
          mkdir release
          cmake -B release --preset="release"
          cmake --build release --config Release
      - name: Install
        shell: pwsh
        run: cmake --install "${{github.workspace}}/release" --config Release
      - name: Build Example
        shell: pwsh
        run: |
          mkdir example/build
          cmake -B example/build -S example
          cmake --build example/build